# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ctarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YZTZOywZNwWD3j5VlCh5MRZzspqqrC1b+CIQB0tKSoqW7Vp4o1jL+aTN6fnS1LCWkxjVQt851lIaVDzpfB+tkKVf3ZTaVUQXpcaq12eSSbiJewUB+KD7IwZgkM6E5sKSxcPnN0wutNqtCUheM/wSND9l7vHI9L9g0qQwyl5e/kXXgD41NonRKQ09NsPO+3IiCI7UQQfsePbARFaV0UgZdgbrg/Q1w7mtYP72t0/hkMxYwXFf1HabQ8FxEU3Vz+yCHPNiNkkpkypkBmMqyk70dbrY7A84IwdTLPF/NovDi9JxE+d6hy1f8EM7AxVtOeqQOWeQPXPHfIF1xF1ezVlFNIcR8JalqC++osfWDO+CyyaCfpX/Iz3MHSUjM66gSgfMUs+C2a9no2S+VSYe1+t8i/EmkIxeCN+n/hhgW7dGZuDrECWPbxbdiU7AY8qmmythkNt+FRVKsQ1PFiliKMUo215gNLxhQZYLWeFz/Q7cPlI1tLvnBOMKd+AogA9Ek8kXAlwbL6Lo/8L6qdgzRMEwMU0Id6XZ0XmadwO6XR2kOLBUDr729whBlmB8zrl+R6QRqNaf52sMv/TXp/3LonNZrpqflsSpsZk25nvyxkaVXmieI6pEjRms0/E78OQtl1RT1gml24M0P3oxTKF8895u8mtZQs9FnmVxeKmb//P0IX8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
