appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YZTZOywZNwWD3j5VlCh5MRZzspqqrC1b+CIQB0tKSoqW7Vp4o1jL+aTN6fnS1LCWkxjVQt851lIaVDzpfB+tkKVf3ZTaVUQXpcaq12eSSbiJewUB+KD7IwZgkM6E5sKSxcPnN0wutNqtCUheM/wSND9l7vHI9L9g0qQwyl5e/kXXgD41NonRKQ09NsPO+3IiCI7UQQfsePbARFaV0UgZdgbrg/Q1w7mtYP72t0/hkMxYwXFf1HabQ8FxEU3Vz+yCHPNiNkkpkypkBmMqyk70dbrY7A84IwdTLPF/NovDi9JxE+d6hy1f8EM7AxVtOeqQOWeQPXPHfIF1xF1ezVlFNIcR8JalqC++osfWDO+CyyaCfpX/Iz3MHSUjM66gSgfMUs+C2a9no2S+VSYe1+t8i/EmkIxeCN+n/hhgW7dGZuDrECWPbxbdiU7AY8qmmythkNt+FRVKsQ1PFiliKMUo215gNLxhQZYLWeFz/Q7cPlI1tLvnBOMKd+AogA9Ek8kXAlwbL6Lo/8L6qdgzRMEwMU0Id6XZ0XmadwO6XR2kOLBUDr729whBlmB8zrl+R6QRqNaf52sMv/TXp/3LonNZrpqflsSpsZk25nvyxkaVXmieI6pEjRms0/E78OQtl1RT1gml24M0P3oxTKF8895u8mtZQs9FnmVxeKmb//P0IX8=}
