travis:
  secure:
    BINSTAR_TOKEN: RCN2EznfGI2ZB12cri/rrUlrW/KbfhLl0EHjgVl2rWobvA0AKLdg+SogXAB3B0sxZiC2KvX45/bHVxkvbQcTLIEBmNOqEdUbSwAvi0KJnJN4SjtA9cZm5LgVtLX0sxee9WZDQ7lTkwFodIgNqJ2A/2OQh3KttYJDJX1Fv8tAfgYSyfqjDLgwOVoNMlhqBcFVD96recNgn4L8NAbh0TgqGnm+7yg+j6GqHiO3EK2OTtwdDp0mimj0f0bvl17RCPAwoLvdm2kdA57P5nsLwU+z0KTKgmILDEvnMgn//Uj/IqVFxomvvGq73YxBPXuS/UfsAGmI9b5WL7lSv4a9u9YpLDuI44dkI8z8FuecbL4yP8qtBLVAtsMvPXPAJk9tsFQgcWgZnG9JJGThM3ZTsuqRDqNILCxZe1Dav774YE4NW31JnlKQiYgrL6/mXhiMzQXuF+uGnP8HHA38pmlakAefJky64njQ4VUzNyhZPls2pZf7kVBs+FziazfMMWfMHxiykLpM64At1K1m2OoRQFjy5cisNJfbquuWti59f+OGCTZdNTnQZ4sWkPWao/km3Yp3Q8zxvQuZunGlyqHK4/LvM9l0763R2eNG/yeof+e5TVUyojsIjMEdWVaDI+HR2hfz2OI4sso/Ks5bh+bty4CWBwrp2CnpDwyBWrtnKnOaxlc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
